# Generated by Django 6.0.1 on 2026-05-30 12:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_barangay_contact_city_contact_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='indirect_contributor',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='phylsis',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='with_disability',
        ),
        migrations.AddField(
            model_name='child',
            name='educational_attainment',
            field=models.CharField(choices=[('No Education', 'No Education'), ('Kindergarten Level', 'Kindergarten Level'), ('Kindergarten Graduate', 'Kindergarten Graduate'), ('Elementary Level', 'Elementary Level'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Level', 'High School Level'), ('High School Graduate', 'High School Graduate'), ('Vocational / TVET', 'Vocational / TVET'), ('College Level', 'College Level'), ('College Graduate', 'College Graduate'), ('Post-College', 'Post-College')], default='Kindergarten', max_length=32),
        ),
        migrations.AddField(
            model_name='child',
            name='monthly_income',
            field=models.CharField(choices=[('Php 20834 and above', 'Php 20834 and above'), ('Minimum wage to Php 20833', 'Minimum wage to Php 20833'), ('Minimum wage and below', 'Minimum wage and below')], default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='occupation',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='relation',
            field=models.CharField(default='child', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='family_resources',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='indigenous_person',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='needs_and_problems',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='pantawid_beneficiary',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='religion',
            field=models.CharField(default='Catholic', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('id', 'ID'), ('signature', 'Signature'), ('document', 'Document')], default='id', max_length=32),
        ),
        migrations.AlterField(
            model_name='parent',
            name='educational_attainment',
            field=models.CharField(choices=[('No Education', 'No Education'), ('Kindergarten Level', 'Kindergarten Level'), ('Kindergarten Graduate', 'Kindergarten Graduate'), ('Elementary Level', 'Elementary Level'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Level', 'High School Level'), ('High School Graduate', 'High School Graduate'), ('Vocational / TVET', 'Vocational / TVET'), ('College Level', 'College Level'), ('College Graduate', 'College Graduate'), ('Post-College', 'Post-College')], default='Kindergarten', max_length=32),
        ),
        migrations.AlterField(
            model_name='parent',
            name='employment',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Not Employed', 'Not Employed')], default='Employed', max_length=32),
        ),
        migrations.AlterField(
            model_name='parent',
            name='monthly_income',
            field=models.CharField(choices=[('Php 20834 and above', 'Php 20834 and above'), ('Minimum wage to Php 20833', 'Minimum wage to Php 20833'), ('Minimum wage and below', 'Minimum wage and below')], max_length=64),
        ),
        migrations.AlterField(
            model_name='parent',
            name='philhealth',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='sector',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PWD', 'PWD'), ('Senior Citizen', 'Senior Citizen'), ('LGBTQIA+', 'LGBTQIA+')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='total_family_income',
            field=models.CharField(choices=[('Php 20834 and above', 'Php 20834 and above'), ('Minimum wage to Php 20833', 'Minimum wage to Php 20833'), ('Minimum wage and below', 'Minimum wage and below')], max_length=64),
        ),
    ]
