# Generated by Django 6.0.1 on 2026-02-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_role_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
    ]
