# Generated by Django 6.0.1 on 2026-02-05 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
