# Generated by Django 6.0.1 on 2026-02-05 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2026, 2, 5, 15, 43, 41, 790890), max_length=180, unique=True),
            preserve_default=False,
        ),
    ]
