# Generated by Django 6.0.1 on 2026-02-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_groups_user_user_permissions_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='exactly_one_identifier',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_when_present',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_when_present',
        ),
    ]
