# Generated by Django 6.0.1 on 2026-02-09 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_user_exactly_one_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
