# Generated by Django 6.0.1 on 2026-02-09 00:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_parent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
