# Generated by Django 6.0.1 on 2026-02-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_parent_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='age',
        ),
    ]
