# Generated by Django 6.0.1 on 2026-02-12 03:54

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_child_age_remove_parent_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='parent',
            name='uuid',
            field=models.CharField(default='2026-rrgdy', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=180)),
                ('middle_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('suffix', models.CharField(blank=True, max_length=180, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.parent')),
            ],
        ),
    ]
