# Generated by Django 6.0.1 on 2026-02-12 04:26

import api.utils.generate_uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_parent_phone_alter_parent_uuid_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='uuid',
            field=models.CharField(default=api.utils.generate_uuid.generate_uuid, editable=False, max_length=10, unique=True),
        ),
    ]
