# Generated by Django 6.0.1 on 2026-02-12 04:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_parent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
