# Generated by Django 6.0.1 on 2026-04-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_parent_barangay_alter_parent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.parent'),
        ),
    ]
