# Generated by Django 6.0.1 on 2026-04-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_image_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='api.parent'),
        ),
    ]
