# Generated by Django 6.0.1 on 2026-04-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_contact_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.parent'),
        ),
    ]
